# Usa a imagem oficial do PostgreSQL
FROM postgres:15

# Variáveis de ambiente básicas (para ambiente local)
ENV POSTGRES_DB=mindtrack
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres

# Expõe a porta padrão do PostgreSQL
EXPOSE 5432
