import { Controller, Get, Post, Res } from '@nestjs/common';
import { PdfService } from './pdf.service';
import type { Response } from 'express';

// TODO -> remover este controller de teste após validar o serviço de PDF

@Controller('pdf')
export class PdfController {
  constructor(private readonly pdfService: PdfService) {}

  @Get()
  async generateTestPdf(@Res() res: Response) {
    const html =
      '<html><body><h1>Test PDF</h1><p>This is a test PDF generated by Puppeteer.</p></body></html>';

    const pdf = await this.pdfService.generatePdf(html);

    res.set({
      'Content-Type': 'application/pdf',
      'Content-Disposition': 'attachment; filename=test.pdf',
      'Content-Length': pdf.buffer.length,
    });

    res.send(pdf);
  }
}
